### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by patricknelson** [brhinescot/Cropper#25]
Not sure if this due to a .NET framework compatibility issue or something. However, one day I started my computer and the application just stopped launching. This is likely due to some kind of software installed by my company (silently and without my knowledge, maybe a framework or something) which may have compatibility issues with the app.  See screenshots and full stack trace below.

- This is the latest version of the app available in releases (v1.11.0)
- I have .NET versions 3.0, 3.5 and 4.7 (release 461814) installed

Steps to reproduce (on my machine only):

1. Run app
2. Icon appears in taskbar
3. Click taskbar icon 2 times 
4. Error message displays with stack trace.

![2018-11-29_15-17-52](https://user-images.githubusercontent.com/4269377/49259442-3a427500-f3ee-11e8-8aa6-779c24547f2b.png)

![2018-11-29_15-18-08](https://user-images.githubusercontent.com/4269377/49259444-3ca4cf00-f3ee-11e8-90a8-523f4410391d.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at Fusion8.Cropper.LayeredForm.PaintLayeredWindow()
   at Fusion8.Cropper.MainCropForm.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at Fusion8.Cropper.CropForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Cropper
    Assembly Version: 1.11.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Brian%20Scott/Cropper/Cropper.exe
----------------------------------------
Cropper.Core
    Assembly Version: 1.11.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Brian%20Scott/Cropper/Cropper.Core.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Cropper.Extensibility
    Assembly Version: 1.11.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Brian%20Scott/Cropper/Cropper.Extensibility.DLL
----------------------------------------
Cropper.BmpFormat
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Brian%20Scott/Cropper/plugins/Cropper.BmpFormat.dll
----------------------------------------
Cropper.ClipboardFormat
    Assembly Version: 1.2.2.0
    Win32 Version: 1.2.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Brian%20Scott/Cropper/plugins/Cropper.ClipboardFormat.dll
----------------------------------------
Cropper.JpgFormat
    Assembly Version: 1.1.1.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Brian%20Scott/Cropper/plugins/Cropper.JpgFormat.dll
----------------------------------------
Cropper.PngFormat
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Brian%20Scott/Cropper/plugins/Cropper.PngFormat.dll
----------------------------------------
Cropper.PrinterOutput
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Brian%20Scott/Cropper/plugins/Cropper.PrinterOutput.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by thomashess** [comment]
Same happens for me, Windows 10. Freshly installed machine, have installed VS, Photoshop etc - just my regular programs. Downloaded version 1.11 and I now get this error when starting the app. :(

Edit: I have .Net 4.7.2 installed

**Comment by ssvenn** [comment]
This happens for me as well, both on 1.10 and 1.11. It's not a fatal error, you can click continue on the exception and click the taskbar button again to show the form which is now 1 pixel tall. You can right click on it and select "reset form" to get it back to normal.
![Screenshot 2019-09-27 at 08 55 34](https://user-images.githubusercontent.com/3955103/65748591-9e17f600-e104-11e9-9d24-a5c08db8709b.png)

It would be great to have that bug squashed though :)

**Comment by kristofzerbe** [comment]
Had the same problem ... just delete the cropper.config in folder C:\Users\USERNAME\appdata\Roaming\cropper to reset the settings and all is working.
